import Head from "next/head";
import Image from "next/image";
import Avatar from "../Components/Avatar";
import Footer from "../Components/Footer";
import { MicrophoneIcon, ViewGridAddIcon } from '@heroicons/react/solid';
import { SearchIcon } from '@heroicons/react/outline';
import { useRef } from "react";
import { useRouter } from "next/router";


export default function Home() {

  const router= useRouter();
      const searchInput= useRef(null);

      const SearchBar= (e)=>{
        e.preventDefault();
        const term= searchInput.current.value;
        console.log(term)
        if (!term) return;
        router.push(`/search?term=${term}`)
      }





  return (
    <div className="flex flex-col h-screen  justify center">
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      {/* Header Left */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* HeaderRight */}
        <div className="flex space-x-5 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>

          {/* Icons */}
          < ViewGridAddIcon className="h-10 w-10 p-2 rounded-full hover:bg-slate-200 cursor-pointer"/>

          {/* Avatar */}

          <Avatar url="https://i0.wp.com/www.hindishayaricollections.com/wp-content/uploads/2020/03/beautifull-girls-images-download-46.jpg?resize=667%2C1000&ssl=1"/>
        </div>
      </header>
      {/* -------------------------------------------------------------------------------------------- */}


      {/* Body */}
      <form className="flex flex-col items-center  flex-grow mt-40 "> 
        <Image src="http://assets.stickpng.com/images/580b57fcd9996e24bc43c51f.png" height={100} width={300} />  

        <div className="flex w-full hover:shadow-lg focus-within:shadow-lg max-w-md  rounded-full border border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500"/>
          <input ref={searchInput} type="text" className="focus:outline-none flex-grow"/>
          <MicrophoneIcon className="h-5"/>
        </div>

        <div className="flex">
          <button onClick={SearchBar} className="btn"> Google Search </button>
          <button  onClick={SearchBar}  className="btn"> I am feeling Lucky</button>
        </div>

      </form>

      {/* Footer */}

     <Footer/>
    </div>
  );
}